#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
# The main focus here is to excersise the STI scripts.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-maven:3}
VERSION=${VERSION-"3"}
S2I_ARGS=${S2I_ARGS:-""}

TEST_APPS=(springboot-hello)
VERSION_COMMAND="env"

extra_tests() {
  echo ""
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/s2i
