#!/bin/bash -e

NAME="maven"
DISPLAY_NAME="Maven"
FROM="maven:%VERSION%"
TYPE="s2i"
VARIANTS="default"
VERSIONS="3-jdk-8"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
