#!/bin/bash -e

NAME="java"
DISPLAY_NAME="Java"
FROM="maven:%VERSION%"
TYPE="s2i"
VARIANTS="default"
VERSIONS="3-jdk-8,3-jdk-9"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
